### ISSUE TITLE
Fix the README so that hyperlinks are not munged.

### ISSUE THREAD

**Issue by shirishag75** [Phant0mas/Guix-on-Hurd#1]
As can be seen instead of http://www.gnu.org/software/guix/ one gets http://www.gnu.org/software/guix/%5D%5BGNU as the link and so on and so forth. It would be good if the README is fixed so such errors are not seen.

**Comment by ragkousism** [comment]
Well thank you for pointing out, but this is caused because of the way github parses the README file. As I don't want to have any non Hurd specific patches in this repo, I will leave it this way for now. 

Edit: I added http://www.gnu.org/software/guix/ at the description.
